[package]
name = "oxideboy"
version = "0.1.0"
authors = ["Sam Day <me@samcday.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
bencher = "0.1"
image = "0.21"
paste = "0.1"

[[bench]]
name = "benches"
harness = false
