[package]
name = "libretro-core"
version = "0.1.0"
authors = ["Sam Day <me@samcday.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libretro-backend = "0.2"

[dependencies.gameboy]
path = "../gameboy"
