[package]
name = "dev"
version = "0.1.0"
authors = ["Sam Day <me@samcday.com>"]

[dependencies]
ratelimit = "0.4.3"
sdl2 = "0.31"

[dependencies.gameboy]
path = "../gameboy"

[profile.release]
debug = true
