[package]
name = "snapshot-tests"
version = "0.1.0"
authors = ["Sam Day <me@samcday.com>"]
edition = "2018"

[dependencies]
bincode = "1.1"
byteorder = "1.3.1"
snap = "0.2"
zstd = "0.4.14"

[dependencies.oxideboy]
path = "../oxideboy"

